### ISSUE TITLE
How to set font pack : regular,italic,bold,bold italic

### ISSUE THREAD

**Issue by kifzuka** [arrowtype/recursive-code-config#11]
![image](https://user-images.githubusercontent.com/28493109/121797044-50b82100-cc26-11eb-81cf-4f9e0093a9dc.png)

how to create pack : regular,italic,bold? and set name to Rec Mono Custom for all? 
because mine indicates a different path to each font

**Comment by arrowtype** [comment]
Hi @kifzuka, thanks for filing the issue, and sorry this issue took me so long to get to! I've now tested it on a windows machine, and things are definitely a little different that I had written in the readme, but they do now work for me. This might be partly because I made some updates to the project today, especially to use the latest version of the library FontTools.

When I build, I can generate the following package:

<img width="448" alt="image" src="https://user-images.githubusercontent.com/45946693/231323273-51058380-ebe7-4870-b040-fe11e1dc135a.png">

It works as expected after installing the font, then restarting my code editor:

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/45946693/231323928-41ed74b6-ff6c-4b06-958e-c080528ac758.png">

That isn't to say that you didn't run into problems. But, if you are willing/hoping to still try this out, can I ask you to do two things?

1. Try the workflow again, please, as documented in the readme. It may be best to delete your local folder and try again from scratch (make sure to separately save your `config.yaml` file if you made changes there!)
2. If you get any errors in the terminal, can you please copy and paste them here, and describe what happened?

If you don't have time or interest to test this again, that is also totally understandable. If you do, though, I'll try help out more quickly on the next round!

**Comment by arrowtype** [comment]
I’m closing this, as it seems like the OP has moved on (which is fine!). If OP or anyone else wants to try this again and comment here or make a new issue, you are more than welcome to. Cheers!
