### ISSUE TITLE
Error when building the fonts on Linux

### ISSUE THREAD

**Issue by larsbs** [arrowtype/recursive-code-config#16]
It seems that either the README is out of date or there's a bug in the script because when you try to run it you get: 

```
Traceback (most recent call last):
  File "scripts/instantiate-code-fonts.py", line 33, in <module>
    fontPath = sys.argv[2]
IndexError: list index out of range
```

And it all seems to be related to this line introduced in the latest commit: https://github.com/arrowtype/recursive-code-config/blob/main/scripts/instantiate-code-fonts.py#L33

EDIT: There also seems to be an issue with the line endings of `scripts/build-all.sh` because if you try to run it as-is in linux you get: 

```
scripts/build-all.sh: line 2: $'\r': command not found
scripts/build-all.sh: line 4: $'\r': command not found
: invalid optionl.sh: line 5: set: -
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
scripts/build-all.sh: line 6: $'\r': command not found
scripts/build-all.sh: line 23: syntax error near unexpected token `$'do\r''
'cripts/build-all.sh: line 23: `for config in $configs; do
```

This gets fixed by changing the line endings from CRLF to simply LF

**Comment by kaushikgopal** [comment]
For the first issue, the script changed recently, to take in a source `font-data` path. In order to generate the font again, you'll need to run this instead:

```
python3 scripts/instantiate-code-fonts.py <premade-configs/casual.yaml> <font-data/Recursive_VF_1.081.ttf>
```

It's [mentioned here](https://github.com/arrowtype/recursive-code-config/blob/main/scripts/instantiate-code-fonts.py#L7).

I've pushed a [PR fix](https://github.com/arrowtype/recursive-code-config/pull/17) that picks a default path. This is only if @arrowtype feels like keeping the previous api makes sense where we don't have to explicitly specify the path.

**Comment by larsbs** [comment]
@arrowtype I just tried with a freshly cloned repo and it worked out the box. Good job! 👍

**Comment by arrowtype** [comment]
That's amazing news – thanks for checking and letting me know, @larsbs!
